// Common Prayer — sample office content for the UI kit.
// Traditional daily-office language (public-domain style), authored for demo.
window.CP_DATA = {
  day: { date: 'July 5, 2026', season: 'The Sixth Sunday after Pentecost', proper: 'Proper 9', color: 'sage' },

  offices: {
    morning: {
      title: 'Morning Prayer',
      icon: 'sunrise',
      opening: "The Officiant begins the service with one or more of the following sentences of Scripture.",
      sentence: "Grace to you and peace from God our Father and from the Lord Jesus Christ.",
      sentenceRef: 'Philippians 1:2',
      confessionRubric: "The following Confession of Sin may then be said; all kneeling.",
      confession: "Almighty and most merciful Father, we have erred and strayed from your ways like lost sheep. We have followed too much the devices and desires of our own hearts. Spare those who confess their faults, restore those who are penitent.",
      versicle: [
        { by: 'Officiant', text: 'Lord, open our lips.' },
        { by: 'People', text: 'And our mouth shall proclaim your praise.', response: true },
      ],
      invitatoryCap: 'C',
      invitatory: "ome, let us sing unto the Lord; let us heartily rejoice in the strength of our salvation. Let us come before his presence with thanksgiving, and show ourselves glad in him with psalms.",
      lessonRef: 'Psalm 95:1–7',
      lesson: "For the Lord is a great God, and a great King above all gods. In his hand are all the corners of the earth, and the strength of the hills is his also. The sea is his, and he made it, and his hands prepared the dry land.",
      collectTitle: 'A Collect for Grace',
      collect: "O Lord, our heavenly Father, almighty and everlasting God, you have brought us in safety to this new day: Defend us by your mighty power, that we may fall into no sin, neither run into any kind of danger.",
      refrain: "In the morning my prayer comes before you; incline your ear to my cry.",
      refrainRef: 'Psalm 88:13',
    },
    noon: {
      title: 'Noonday Prayer',
      icon: 'sun',
      opening: "The Officiant begins",
      sentence: "O God, make speed to save us. O Lord, make haste to help us.",
      sentenceRef: 'Psalm 70:1',
      confessionRubric: "A pause is kept.",
      confession: "Blessed Savior, at this hour you hung upon the cross, stretching out your loving arms: Grant that all the peoples of the earth may look to you and be saved.",
      versicle: [
        { by: 'Officiant', text: 'Let the words of my mouth be acceptable.' },
        { by: 'People', text: 'And the meditation of my heart, O Lord.', response: true },
      ],
      invitatoryCap: 'B',
      invitatory: "lessed are they who dwell in your house; they will always be praising you. Blessed are those whose strength is in you, whose hearts are set on the pilgrims' way.",
      lessonRef: 'Psalm 84:4–5',
      lesson: "For a day in your courts is better than a thousand elsewhere. I would rather stand at the threshold of the house of my God than dwell in the tents of the wicked.",
      collectTitle: 'A Collect for the Renewal of Life',
      collect: "Lord, in the middle of my everyday life of jobs and commitments, it is easy to forget that you have called me to partner in your great work of salvation. I remind myself of that reality now.",
      refrain: "At noon I cry out in my distress, and the Lord hears my voice.",
      refrainRef: 'Psalm 55:17',
    },
    evening: {
      title: 'Evening Prayer',
      icon: 'moon',
      opening: "The Officiant begins the service",
      sentence: "Let my prayer be set forth in your sight as incense, the lifting up of my hands as the evening sacrifice.",
      sentenceRef: 'Psalm 141:2',
      confessionRubric: "The following Confession of Sin may then be said.",
      confession: "Most merciful God, we confess that we have sinned against you in thought, word, and deed, by what we have done, and by what we have left undone. Have mercy on us and forgive us.",
      versicle: [
        { by: 'Officiant', text: 'O God, make speed to save us.' },
        { by: 'People', text: 'O Lord, make haste to help us.', response: true },
      ],
      invitatoryCap: 'O',
      invitatory: " gracious Light, pure brightness of the everliving Father in heaven: now as we come to the setting of the sun, and our eyes behold the vesper light, we sing your praises, O God.",
      lessonRef: 'Phos hilaron',
      lesson: "You are worthy at all times to be praised by happy voices, O Son of God, O Giver of life, and to be glorified through all the worlds.",
      collectTitle: 'A Collect for Peace',
      collect: "O God, from whom all holy desires, all good counsels, and all just works proceed: Give to your servants that peace which the world cannot give, that our hearts may be set to obey your commandments.",
      refrain: "Into your hands I commend my spirit; you have redeemed me, O Lord, O God of truth.",
      refrainRef: 'Psalm 31:5',
    },
  },
};
